### ISSUE TITLE
Issue with Coil power output

### ISSUE THREAD

**Issue by worldpeace-germany** [cobra18t/CobraPin#5]
Hi,

on testing flipper fingers some smoke came from the board :-( I would like to understand what went wrong to avoid this mistake in the future. I assume one of the transistors is burned.

Question 1:
The documentation says the max fuse used for the coil power should be 10A. I used one of the 10A fuses. After the issue the fuse is still okay.  Aren't the transistors rated for 10A that they burn? My understanding here is that the fuse should protect the electric components, why is it not?

Question 2:
The output in question (main coil, not hold coil) shows now constantly 24V as output (I am using for my test 24V power supply). Based on that I assume that my transistor is dead for that output. The strange thing is the yellow LED indicating that the transistor is switching is behaving like one for a fully working output. Which means it is off all the time unless I press my trigger button then it is turned on. Either I misunderstood a detail of that yellow LED or the transistor is still okay, but then I should not see constantly 24V on the output. Can that behavior be explained?

Question 3:
At the moment I have no idea how it came to the situation. The  mpf code is basically from the tutorial. So the main coil is only powered for a few ms (default value, I assume 10ms) and the hold coil powered constantly (while keeping the button pressed). The coil is a FL-11629-50V coil, I measured 3.5 Ohm and 135 Ohm of resistance. Which would mean for 24V power supply 6.9A and 170mA. I had a look at https://flippers.com/coil-resistance.html , they say 4/133 Ohm, so no big difference. In the text they say "blue, strongest", the paper wrapping of mine is orange which would be according to their chart a FL-15411 coil with 4.2/150 Ohm. Again no big difference to what I measured. Any idea what mistake I could have made? Would like to avoid killing more outputs.... 

Thanks!

**Comment by worldpeace-germany** [comment]
Okay, found my mistake, I had a short connection on the coil when the switch was pressed. That answers question 3. Question 1 and 2 remain valid. I don't mind too much for now if I have one coil output less, the price you pay when learning new things. Any guess on what I might have fried up?

**Comment by cobra18t** [comment]
Re Q1:
The fuses are slow blow fuses. They can actually withstand far more than 10A for a very short amount of time. The transistor can only handle maybe 40A but burns out instantly above that. Since you had a hard short, you had far too much current at once and the transistor burned. It was a short enough pulse, though that the fuse survived. I would evaluate your current draws on that bank and consider a lower fuse current. Many people add inline fuses to each flipper.

Re Q2: The yellow LEDs are on the logic side of the FET. They indicate the *Command* to the FET, not the *Output* of the FET. So even though the FET is broken, you can see the command is fine. This enables you to evaluate proper operation on the logic side before applying coil power. I believe your FET is broken.

**Comment by worldpeace-germany** [comment]
thanks, understood. then one day I will change the FET.
