### ISSUE TITLE
Seek guidance to size power supply

### ISSUE THREAD

**Issue by worldpeace-germany** [cobra18t/CobraPin#6]
Hello,

I seek some guidance what is the right size (wattage) of the power supply to choose. I neither want to buy a crazy big power supply, neither it should not have too little wattage that I start buying a second one in half a year.

My considerations are the following:

- Voltage: 48V
- 3 coils in parallel to be fired at max simultaneously (2 flipper fingers plus one sling shot, bumper, etc)
- Coils 26-1200 (10 Ohm), 23-800 ( 4 Ohm) for bumpers, etc.
- FL-11629 (4 Ohm) for flipper fingers

I have no clue yet if the coils for 48V are a good choice, chicken and egg problem. Should be just a "normal" or "average" coil for these purposes.

A 4 Ohm coil would draw 12A, if I have three of them at the same time it is 36A, if the 10 Ohm coil is good for my purpose I have 2*12A + 5A = 29A of electrical current. That would be 1400 - 1800 W - I cannot believe that I need that. Of course current will only be drawn for 20-40ms and we have the large capacitors on the cobra board to buffer. I have no idea how to factor that into my thoughts.

Any guidance, what coils would be good, how to come to a reasonable (and somewhat reliable) result?

About the coils, anything I need to obey that I don't fry a mos-fet on the cobra board?

How powerful are the power supplies of the people reading this?

Thanks!

**Comment by cobra18t** [comment]
I have a 48V 7.5A supply. A 10 or 12A would be fine as well. The average load is not actually that high, it is just very spiky. The capacitors help supply those load spikes.

A 4ohm coil should not really draw 12A for even 20-40ms. Remember, the coil acts like an inductor which resists instantaneous changes to current. So if you left the coil on, sure it would get to a 12A draw eventually, but the pulse is over or at least nearly over before then. If you do reach 12A for any appreciable amount of time, you should be blowing fuses.

In the image below, the current never reaches steady state current since the pulse ends before the inductor charges all the way. I have not actually measured the current waveform of these particular coils, though. In the end, a 7.5 to 12A supply "just works" for pinball.

As far as not frying FETs, triple check your pinout and note that each connector has 8 coil outputs but 9 pins. One is a "key" pin that is in a different location on each bank. The key is marked by an asterisk.

Also, coil diodes must always "point" to power. So the cathode must always face the high voltage side. If you get this wrong, you will short 48V to GND through a forward biased diode when you first fire that coil which will surely fry the FET.

![PWM_Graph-4-600x360](https://user-images.githubusercontent.com/1877729/230288248-adbf48eb-3db9-4a9f-8705-94576dc4ace4.jpg)

**Comment by cobra18t** [comment]
As far as flipper coils, here is the common guidance:

FL-11753 (Yellow)- Used with short flippers and close shots....think Twilight Zone 2" upper flipper
FL-11722 (Green) - Used for close shots near drop targets...think Twilight Zone 3" upper flipper
FL-11630 (Red) - The standard, most commonly used coil...F-14 main flippers
FL-15411 (Orange) - Used for long playfield shots...Twilight Zone main flippers
FL-11629 (Blue) - Used for long shots and high ramps...Demolition Man main flippers

If you have the latest OPP firmware (2.4.0.0 or later is recommended), you can change the pulse power through MPF to reduce the power of a flipper to tune it. That is what I am doing on my Tag Team.

**Comment by worldpeace-germany** [comment]
As usual a perfect answer in no time at all. Thanks very much!
